

import os

GENERAL_KAFKA_BOOTSTRAP_SERVERS = os.getenv(
    "GENERAL_KAFKA_BOOTSTRAP_SERVERS", "general-kafka1:9092")
GENERAL_MINIO_ENDPOINT = os.getenv(
    "GENERAL_MINIO_ENDPOINT", "general-minio1:9000")
GENERAL_MINIO_ACCESS_KEY = os.getenv("GENERAL_MINIO_ACCESS_KEY", "admin")
GENERAL_MINIO_SECRET_KEY = os.getenv("GENERAL_MINIO_SECRET_KEY", "password123")
GENERAL_HUNYUAN_AI_WORKER_HUNYUAN_ROOT = os.getenv(
    "GENERAL_HUNYUAN_AI_WORKER_HUNYUAN_ROOT", "/app/src/Hunyuan3D/weights")
GENERAL_HUNYUAN_AI_WORKER_SCRIPT_ROOT = os.getenv(
    "GENERAL_HUNYUAN_AI_WORKER_SCRIPT_ROOT", "/app/src")
GENERAL_HUNYUAN_AI_WORKER_SERVER_PORT = int(
    os.getenv("GENERAL_HUNYUAN_AI_WORKER_SERVER_PORT", 80))

GENERAL_OBJ_GENERATE_SERVICE_IP_ADDRESS = os.getenv(
    "GENERAL_OBJ_GENERATE_SERVICE_IP_ADDRESS", "general-obj-generate-service")
