version: "3.8"

services:
    polyroom-ai-worker:
        build:
            context: ./middleware/general/polyroom-ai-worker
            dockerfile: dockerfile
        container_name: polyroom-ai-worker
        hostname: polyroom-ai-worker
        restart: always
        ports:
            - "30020:80"
        extra_hosts:
            - "host.docker.internal:host-gateway"
        depends_on:
            - general-kafka1
            - general-minio1
        environment:
            - GENERAL_KAFKA_BOOTSTRAP_SERVERS=general-kafka1:9092
            - GENERAL_MINIO_ENDPOINT=general-minio1:9000
            - GENERAL_OBJ_GENERATE_SERVICE_IP_ADDRESS=host.docker.internal:10001
        volumes:
            - F:/AI/PolyRoom:/app/src/Polyroom
        networks:
            - general-network
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: all
                          capabilities: [gpu]
    hunyuan-ai-worker:
        build:
            context: ./middleware/general/hunyuan-ai-worker
            dockerfile: dockerfile
        container_name: hunyuan-ai-worker
        hostname: hunyuan-ai-worker
        restart: always
        ports:
            - "30010:80"
        extra_hosts:
            - "host.docker.internal:host-gateway"
        depends_on:
            - general-kafka1
            - general-minio1
        environment:
            - GENERAL_KAFKA_BOOTSTRAP_SERVERS=general-kafka1:9092
            - GENERAL_MINIO_ENDPOINT=general-minio1:9000
            - GENERAL_OBJ_GENERATE_SERVICE_IP_ADDRESS=host.docker.internal:10001
        volumes:
            - F:/AI/Hunyuan3D-2:/app/src/Hunyuan3D
        networks:
            - general-network
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: all
                          capabilities: [gpu]

    general-minio1:
        image: minio/minio:latest
        container_name: general-minio1
        hostname: general-minio1
        restart: always
        ports:
            - "30000:9000" # API Port
            - "30001:9001" # Web Console Port
        environment:
            MINIO_ROOT_USER: admin
            MINIO_ROOT_PASSWORD: password123
        volumes:
            - ./data/local/general/volumes/minio1:/data
        command: server /data --console-address ":9001"
        networks:
            - general-network
    general-zookeeper1:
        image: confluentinc/cp-zookeeper:7.8.0
        container_name: general-zookeeper1
        hostname: general-zookeeper1
        restart: always
        ports:
            - "30004:2181"
        environment:
            - ZOOKEEPER_CLIENT_PORT=2181
            - ZOOKEEPER_SERVER_ID=1
            - ALLOW_ANONYMOUS_LOGIN=yes
        volumes:
            - ./data/local/general/volumes/zookeeper1:/var/lib/zookeeper/data
        networks:
            - general-network
    general-kafka1:
        image: confluentinc/cp-kafka:7.8.0
        container_name: general-kafka1
        hostname: general-kafka1
        restart: always
        ports:
            - "30005:9092"
            - "29092:29092"
        depends_on:
            - general-zookeeper1
        environment:
            - KAFKA_BROKER_ID=1
            - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
            - ALLOW_PLAINTEXT_LISTENER=yes
            - KAFKA_ZOOKEEPER_CONNECT=general-zookeeper1:2181
            - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
            - KAFKA_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_INTERNAL://:29092
            - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://general-kafka1:9092,PLAINTEXT_INTERNAL://localhost:29092
        volumes:
            - ./data/local/general/volumes/kafka1:/var/lib/kafka/data
        networks:
            - general-network
networks:
    general-network:
        name: general-network
        driver: bridge
