server:
    port: ${GENERAL_OBJ_GENERATE_SERVICE_SERVER_PORT}
spring:
    application:
        name: general-obj-generate-service
    jpa:
        hibernate.ddl-auto: none
        properties.hibernate.jdbc.time_zone: ${GENERAL_OBJ_GENERATE_SERVICE_JPA_TIMEZONE}
    datasource:
        url: jdbc:postgresql://${GENERAL_OBJ_GENERATE_SERVICE_DATASOURCE_DB_URL}:${GENERAL_OBJ_GENERATE_SERVICE_DATASOURCE_DB_PORT}/${GENERAL_OBJ_GENERATE_SERVICE_DATASOURCE_DB_SCHEMA}
        username: ${GENERAL_OBJ_GENERATE_SERVICE_DATASOURCE_USERNAME}
        password: ${GENERAL_OBJ_GENERATE_SERVICE_DATASOURCE_PASSWORD}
        driver-class-name: org.postgresql.Driver
        liquibase:
            change-log: classpath:db/changelog/db.changelog-master.yaml
    config:
        import: "optional:configserver:"
    cloud:
        gateway:
            enabled: true
        config:
            discovery:
                enabled: true
                service-id: ${GENERAL_CONFIG_MAPPING_SERVER_HOSTNAME}
            username: ${GENERAL_CONFIG_MAPPING_SECURITY_USERNAME}
            password: ${GENERAL_CONFIG_MAPPING_SECURITY_PASSWORD}
eureka:
    instance:
        prefer-ip-address: false
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://admin:${GENERAL_SERVICE_REGISTRY_SECURITY_PASSWORD}@${GENERAL_SERVICE_REGISTRY_SERVER_IP_ADDRESS}:${GENERAL_SERVICE_REGISTRY_SERVER_PORT}/eureka
properties:
    security: dummy
    cors:
        allowed-origins: ${GENERAL_OBJ_GENERATE_SERVICE_CORS_ALLOWED_ORIGINS}
grpc:
    server:
        port: ${GENERAL_OBJ_GENERATE_SERVICE_GRPC_PORT}
minio:
    endpoint: http://localhost:30000 # Updated port
    access-key: admin
    secret-key: password123
    bucket-name: 3d-projects