

import os

GENERAL_RABBITMQ_HOST = os.getenv("GENERAL_RABBITMQ_HOST", "general-rabbitmq")
GENERAL_RABBITMQ_PORT = int(os.getenv("GENERAL_RABBITMQ_PORT", 5672))
GENERAL_MINIO_ENDPOINT = os.getenv(
    "GENERAL_MINIO_ENDPOINT", "general-minio1:9000")
GENERAL_MINIO_ACCESS_KEY = os.getenv("GENERAL_MINIO_ACCESS_KEY", "admin")
GENERAL_MINIO_SECRET_KEY = os.getenv("GENERAL_MINIO_SECRET_KEY", "password123")
GENERAL_HUNYUAN_AI_WORKER_HUNYUAN_ROOT = os.getenv(
    "GENERAL_HUNYUAN_AI_WORKER_HUNYUAN_ROOT", "/app/src/Hunyuan3D/weights")
GENERAL_HUNYUAN_AI_WORKER_QUEUE_TO_EXCHANGE = os.getenv(
    "GENERAL_HUNYUAN_AI_WORKER_QUEUE_TO_EXCHANGE", "obj-generation-queue")
GENERAL_HUNYUAN_AI_WORKER_QUEUE_FROM_NAME = os.getenv(
    "GENERAL_HUNYUAN_AI_WORKER_QUEUE_FROM_NAME", "hunyuan-worker-queue")

GENERAL_OBJ_GENERATE_SERVICE_IP_ADDRESS = os.getenv(
    "GENERAL_OBJ_GENERATE_SERVICE_IP_ADDRESS", "general-obj-generate-service")
