

import os

GENERAL_RABBITMQ_HOST = os.getenv("GENERAL_RABBITMQ_HOST", "localhost")
GENERAL_RABBITMQ_PORT = int(os.getenv("GENERAL_RABBITMQ_PORT", 30002))
GENERAL_MINIO_ENDPOINT = os.getenv("GENERAL_MINIO_ENDPOINT", "localhost:30000")
GENERAL_MINIO_ACCESS_KEY = os.getenv("GENERAL_MINIO_ACCESS_KEY", "admin")
GENERAL_MINIO_SECRET_KEY = os.getenv("GENERAL_MINIO_SECRET_KEY", "password123")
GENERAL_HUNYUAN_AI_WORKER_HUNYUAN_ROOT = os.getenv(
    "GENERAL_HUNYUAN_AI_WORKER_HUNYUAN_ROOT", "/app/Hunyuan3D")
GENERAL_HUNYUAN_AI_WORKER_PYTHON_EXEC = os.getenv(
    "GENERAL_HUNYUAN_AI_WORKER_PYTHON_EXEC", "python")
