# Use the official PyTorch image with CUDA 12.1 (Adjust if your GPU needs a different CUDA version)
FROM pytorch/pytorch:2.1.0-cuda12.1-cudnn8-runtime

ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Etc/UTC

# Set working directory
WORKDIR /
RUN mkdir -p /app
WORKDIR /app

# Install system dependencies required for OpenCV, 3D rendering, and Git
RUN apt-get update && apt-get install -y \
    git \
    libgl1 \
    libglib2.0-0 \
    libopengl0 \
    libegl1 \
    build-essential \
    gcc \
    g++ \
    && rm -rf /var/lib/apt/lists/*


COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt


COPY ./packages/* /app/packages/
RUN pip install /app/packages/mmcv-2.1.0-cp310-cp310-manylinux1_x86_64.whl
RUN pip install /app/packages/opencv_python_headless-4.13.0.92-cp37-abi3-manylinux_2_28_x86_64.whl
RUN pip install --no-cache-dir -i https://pypi.tuna.tsinghua.edu.cn/simple numpy==1.24.4 trimesh==4.4.1 shapely==2.0.4 mapbox_earcut mmdet==3.3.0 mmsegmentation==1.2.2
RUN pip install numpy==1.24.4

COPY ./src/* /app/src/
EXPOSE 80

ENTRYPOINT ["python", "/app/src"]